In [2]:
#https://machinelearningmastery.com/implement-simple-linear-regression-scratch-python/
import pandas as pd
pd

<module 'pandas' from 'C:\\Users\\G555903\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>

In [3]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\G555903\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
pd.read_csv('C:\development\python_training\Datasets\insurance.csv')

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [6]:
import sys,os

In [347]:
file_path= 'C:\development\python_training\Datasets\insurance.csv'
table = pd.read_csv(file_path)
table

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
table.head(15)

age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
5    31  female  25.740         0     no  southeast   3756.62160
6    46  female  33.440         1     no  southeast   8240.58960
7    37  female  27.740         3     no  northwest   7281.50560
8    37    male  29.830         2     no  northeast   6406.41070
9    60  female  25.840         0     no  northwest  28923.13692
10   25    male  26.220         0     no  northeast   2721.32080
11   62  female  26.290         0    yes  southeast  27808.72510
12   23    male  34.400         0     no  southwest   1826.84300
13   56  female  39.820         0     no  southeast  11090.71780
14   27    male     NaN         0    yes  southeast  39611.75770

In [17]:
table.index

RangeIndex(start=0, stop=1338, step=1)

In [16]:
table.loc[:,['age','sex']]

age     sex
0      19  female
1      18    male
2      28    male
3      33    male
4      32    male
...   ...     ...
1333   50    male
1334   18  female
1335   18  female
1336   21  female
1337   61  female

[1338 rows x 2 columns]

In [18]:
table[['age','sex','bmi']]

age     sex     bmi
0      19  female  27.900
1      18    male  33.770
2      28    male  33.000
3      33    male  22.705
4      32    male  28.880
...   ...     ...     ...
1333   50    male  30.970
1334   18  female  31.920
1335   18  female  36.850
1336   21  female  25.800
1337   61  female  29.070

[1338 rows x 3 columns]

In [19]:
table.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [20]:
table.abs

<bound method NDFrame.abs of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

In [21]:
table.apply(np.sum,axis=0)

age                                                     52459
sex         femalemalemalemalemalefemalefemalefemalemalefe...
bmi                                                   40867.8
children                                                 1465
smoker      yesnonononononononononoyesnonoyesnonononoyesno...
region      southwestsoutheastsoutheastnorthwestnorthwests...
charges                                           1.77558e+07
dtype: object

In [22]:
table.shape

(1338, 7)

In [23]:
table.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [26]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int32)

In [28]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]], np.int64)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [29]:
x.shape

(3, 3)

In [30]:
x[1,2] #Indexing

6

In [31]:
table.loc[5,'age'] #indexing in dataframe

31

In [32]:
table.iloc[5,5]  ##indexing in dataframe

'southeast'

In [33]:
y=x[:,1]  #all rows and second column selected
y

array([2, 5, 8], dtype=int64)

In [34]:
y[0]=9
y
x

array([[1, 9, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [35]:
table.iloc[:,-1:]  # all rows and last columns selected.

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [36]:
x=np.array(range(0,27)).reshape(-1,3,3,3)
x

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]])

In [37]:
x.shape

(1, 3, 3, 3)

In [38]:
x.max(axis=-4)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
x.argmax(axis=3)

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]], dtype=int64)

In [40]:
x.flags #Ask vaibhav what is the meaning of this output.%%%%%%%

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [41]:
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [42]:
table.max(axis=1)

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Length: 1338, dtype: float64

In [43]:
def get_young(x):
    if x>=18:
        return "adult"
    else:
        return "adolescent"

In [44]:
new_feature=table['age'].apply(get_young)

In [45]:
type(new_feature)

pandas.core.series.Series

In [46]:
table['is_young']=new_feature

In [47]:
def round_off(x):
    int_value=int(x)
    if (x-int_value)>=0.5:
        x=int_value+1
        return x
    else:
        return int_value


In [48]:
round_off(5.9)

6

In [49]:
new_round_off=table['charges'].apply(round_off)

In [50]:
table['RoundOff']=new_round_off

In [51]:
table

age     sex     bmi  children smoker     region      charges is_young  \
0      19  female  27.900         0    yes  southwest  16884.92400    adult   
1      18    male  33.770         1     no  southeast   1725.55230    adult   
2      28    male  33.000         3     no  southeast   4449.46200    adult   
3      33    male  22.705         0     no  northwest  21984.47061    adult   
4      32    male  28.880         0     no  northwest   3866.85520    adult   
...   ...     ...     ...       ...    ...        ...          ...      ...   
1333   50    male  30.970         3     no  northwest  10600.54830    adult   
1334   18  female  31.920         0     no  northeast   2205.98080    adult   
1335   18  female  36.850         0     no  southeast   1629.83350    adult   
1336   21  female  25.800         0     no  southwest   2007.94500    adult   
1337   61  female  29.070         0    yes  northwest  29141.36030    adult   

      RoundOff  
0        16885  
1         1726  
2         4449  
3        21984  
4         3867  
...        ...  
1333     10601  
1334      2206  
1335      1630  
1336      2008  
1337     29141  

[1338 rows x 9 columns]

In [52]:
#age greter than 18 

In [53]:
table[(table.sex=="female") & (table.smoker=="yes")]

age     sex     bmi  children smoker     region      charges is_young  \
0      19  female  27.900         0    yes  southwest  16884.92400    adult   
11     62  female  26.290         0    yes  southeast  27808.72510    adult   
23     34  female  31.920         1    yes  northeast  37701.87680    adult   
58     53  female  22.880         1    yes  southeast  23244.79020    adult   
64     20  female  22.420         0    yes  northwest  14711.74380    adult   
...   ...     ...     ...       ...    ...        ...          ...      ...   
1308   25  female  30.200         0    yes  southwest  33900.65300    adult   
1313   19  female  34.700         2    yes  southwest  36397.57600    adult   
1314   30  female  23.655         3    yes  northwest  18765.87545    adult   
1323   42  female  40.370         2    yes  southeast  43896.37630    adult   
1337   61  female  29.070         0    yes  northwest  29141.36030    adult   

      RoundOff  
0        16885  
11       27809  
23       37702  
58       23245  
64       14712  
...        ...  
1308     33901  
1313     36398  
1314     18766  
1323     43896  
1337     29141  

[115 rows x 9 columns]

In [66]:
#Mean

def mean(x):
    return sum(x)/int(len(x))


In [55]:
type(table['charges'])

pandas.core.series.Series

In [56]:
type(table[['charges']])

pandas.core.frame.DataFrame

In [57]:
table.drop(columns=['RoundOff'],inplace=True)

In [58]:
table

age     sex     bmi  children smoker     region      charges is_young
0      19  female  27.900         0    yes  southwest  16884.92400    adult
1      18    male  33.770         1     no  southeast   1725.55230    adult
2      28    male  33.000         3     no  southeast   4449.46200    adult
3      33    male  22.705         0     no  northwest  21984.47061    adult
4      32    male  28.880         0     no  northwest   3866.85520    adult
...   ...     ...     ...       ...    ...        ...          ...      ...
1333   50    male  30.970         3     no  northwest  10600.54830    adult
1334   18  female  31.920         0     no  northeast   2205.98080    adult
1335   18  female  36.850         0     no  southeast   1629.83350    adult
1336   21  female  25.800         0     no  southwest   2007.94500    adult
1337   61  female  29.070         0    yes  northwest  29141.36030    adult

[1338 rows x 8 columns]

In [59]:
table[['age','charges']].apply(mean)#lambda x:mean(x),axis=0)

age           39.207025
charges    13270.422265
dtype: float64

In [60]:
mean_val=table[['age','charges']].apply(mean)['charges']
mean_val

13270.422265141257

In [61]:
#sample variance
def variance(values,m):
    sample_var=sum([(x-m)**2 for x in values])
    return sample_var


In [62]:
mean_val

13270.422265141257

In [63]:
table[['charges']].apply(variance,args=([mean_val])) #to pass all the extra values other than charges put it in arguments in the order.

charges    1.960742e+11
dtype: float64

In [64]:
table

age     sex     bmi  children smoker     region      charges is_young
0      19  female  27.900         0    yes  southwest  16884.92400    adult
1      18    male  33.770         1     no  southeast   1725.55230    adult
2      28    male  33.000         3     no  southeast   4449.46200    adult
3      33    male  22.705         0     no  northwest  21984.47061    adult
4      32    male  28.880         0     no  northwest   3866.85520    adult
...   ...     ...     ...       ...    ...        ...          ...      ...
1333   50    male  30.970         3     no  northwest  10600.54830    adult
1334   18  female  31.920         0     no  northeast   2205.98080    adult
1335   18  female  36.850         0     no  southeast   1629.83350    adult
1336   21  female  25.800         0     no  southwest   2007.94500    adult
1337   61  female  29.070         0    yes  northwest  29141.36030    adult

[1338 rows x 8 columns]

In [65]:
B1 = sum((x(i) - mean(x)) * (y(i) - mean(y))) / sum( (x(i) - mean(x))^2 )

NameError: name 'i' is not defined

In [ ]:
(y(i) - mean(y))

In [111]:
def get_mean(x):
    mean_value=sum(x)/len(x)
    return mean_value

In [119]:
mean_charges=table[['charges']].apply(get_mean)

In [120]:
mean_charges['charges']

13270.422265141257

In [126]:
mean_charges

charges    13270.422265
dtype: float64

In [132]:
mean_charges=mean_charges.values[0]
mean_charges

13270.422265141257

## Deviation function

In [281]:
def get_deviation(row_item,mean_val):
    deviation=(row_item-mean_val)
    return deviation

In [273]:
deviation=table['charges'].apply(get_deviation,args=([mean_charges]))

In [283]:
deviation**2 ## Sqaures to weigh more dispersion value and also to avoid nullifying of positive and negative values

0       1.306462e+07
1       1.332840e+08
2       7.780934e+07
3       7.593464e+07
4       8.842707e+07
            ...     
1333    7.128227e+06
1334    1.224219e+08
1335    1.355033e+08
1336    1.268434e+08
1337    2.518867e+08
Name: charges, Length: 1338, dtype: float64

In [284]:
(sum(deviation**2)/(len(deviation**2)))**(1/2)

12105.484975561605

In [286]:
table.charges.std()

12110.011236693994

In [288]:
y_charges_dev=deviation**2
y_charges_dev

0       1.306462e+07
1       1.332840e+08
2       7.780934e+07
3       7.593464e+07
4       8.842707e+07
            ...     
1333    7.128227e+06
1334    1.224219e+08
1335    1.355033e+08
1336    1.268434e+08
1337    2.518867e+08
Name: charges, Length: 1338, dtype: float64

## Calculating co_efficients 

## B1 = sum((x(i) - mean(x)) * (y(i) - mean(y))) / sum( (x(i) - mean(x))^2 )


In [289]:
def get_covariance(row_item,mean_x,mean_y):
#     print(row_item)
#     print(row_item.values)
    xi=row_item.values[0]
    yi=row_item.values[1]
#     print(xi,yi)
    covariance=(xi-mean_x)*(yi-mean_y)
#     print(covariance)
#     print("\n")
    return covariance

In [290]:
age_mean=table[['age']].apply(get_mean).values[0]
age_mean

39.20702541106129

In [291]:
age_covariance=table[['age','charges']].apply(get_covariance,args=([age_mean,mean_charges]),axis=1)## understanding axis

In [301]:
age_deviation=table[['age']].apply(get_deviation,args=([age_mean]))
age_deviation

age
0    -20.207025
1    -21.207025
2    -11.207025
3     -6.207025
4     -7.207025
...         ...
1333  10.792975
1334 -21.207025
1335 -21.207025
1336 -18.207025
1337  21.792975

[1338 rows x 1 columns]

In [310]:
sum((age_deviation**2).values)

array([263925.65396114])

In [313]:
age_coeeficient=sum(age_covariance)/sum((age_deviation**2).values)
age_coeeficient

array([257.72261867])

## Another way of calculating co_efficients 

## B1 = sum((x(i) - mean(x)) * (y(i) - mean(y))) / sum( (x(i) - mean(x))^2 )


In [319]:
p=table[['age']].apply(get_deviation,args=([age_mean]))
p

age
0    -20.207025
1    -21.207025
2    -11.207025
3     -6.207025
4     -7.207025
...         ...
1333  10.792975
1334 -21.207025
1335 -21.207025
1336 -18.207025
1337  21.792975

[1338 rows x 1 columns]

In [320]:
q=table[['charges']].apply(get_deviation,args=([mean_charges]))
q

charges
0      3614.501735
1    -11544.869965
2     -8820.960265
3      8714.048345
4     -9403.567065
...            ...
1333  -2669.873965
1334 -11064.441465
1335 -11640.588765
1336 -11262.477265
1337  15870.938035

[1338 rows x 1 columns]

In [324]:
sum((p.values*q.values))/sum(p.values**2)

array([257.72261867])

In [247]:
table.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges',
       'is_young'],
      dtype='object')

In [248]:
continuous_cols=['age','bmi','children']


In [325]:
# Calculating B1
def calculate_coeeficient(feature,target):
    co_ef=sum((feature.values*target.values))/sum(feature.values**2)
    return co_ef

In [357]:
np.sum(table[['bmi']].isna())

bmi    5
dtype: int64

In [358]:
table.dropna(subset=['bmi'],inplace=True)

In [359]:
np.sum(table[['bmi']].isna())

bmi    0
dtype: int64

In [370]:
def coef_B1():
    q=table[['charges']].apply(get_deviation,args=([mean_charges]))
    co_effiecients=[]
    for col in continuous_cols:
        table.dropna(subset=[col],inplace=True)
        col_mean=table[[col]].apply(get_mean).values[0]
        p=table[[col]].apply(get_deviation,args=([col_mean]))
        coef=calculate_coeeficient(p,q)[0]
        print("Coeeficient for {} is {}".format(col,coef))
        co_effiecients.append(coef)
        return co_effiecients

Coeeficient for age is 255.62441741687826
Coeeficient for bmi is 385.9534657139147
Coeeficient for children is 699.6660150400287


In [371]:
target_mean=table[['charges']].apply(get_mean)
target_mean

charges    13193.017501
dtype: float64

In [408]:
def coef_B1(continuous_cols):
    q=table[['charges']].apply(get_deviation,args=([mean_charges]))
    co_effiecients=[]
    for col in continuous_cols:
        table.dropna(subset=[col],inplace=True)
        col_mean=table[[col]].apply(get_mean).values[0]
        p=table[[col]].apply(get_deviation,args=([col_mean]))
        coef=calculate_coeeficient(p,q)[0]
        print("Coeeficient for {} is {}".format(col,coef))
        co_effiecients.append(coef)
    return co_effiecients
coef_B1(continuous_cols)

Coeeficient for age is 255.62441741687826
Coeeficient for bmi is 385.9534657139147
Coeeficient for children is 699.6660150400287


[255.62441741687826, 385.9534657139147, 699.6660150400287]

## Calculating bias 
## B0 = mean(y) - B1 * mean(x)

In [407]:
def co_efficientB0(continuous_cols):
    target_mean=table[['charges']].apply(get_mean)
    co_effiecients1=[]
    for col in continuous_cols:
        table.dropna(subset=[col],inplace=True)
        col_mean=table[[col]].apply(get_mean).values[0]
        coef_B1=table[col].apply(coef_B1).values
        print(coef_B1)
        coef1=target_mean-(coef_B1*col_mean)
        print("CoeeficientB0 for {} is {}".format(col,coef1))
        co_effiecients1.append(coef1)
    return co_effiecients1
co_efficientB0(continuous_cols)   

UnboundLocalError: local variable 'coef_B1' referenced before assignment

##B0 for age

In [402]:
#B0 = mean(y) - B1 * mean(x)

target_mean=table[['charges']].apply(get_mean)
print(target_mean)

charges    13193.017501
dtype: float64


In [404]:
age_mean=table[['age']].apply(get_mean).values[0]
age_mean

39.192048012003

In [420]:
target_mean=table[['charges']].apply(get_mean)
co_effiecientsB1=[]
co_effiecientsB0=[]
for col in continuous_cols:
    table.dropna(subset=[col],inplace=True)
    col_mean=table[[col]].apply(get_mean).values[0]
    p=table[[col]].apply(get_deviation,args=([col_mean]))
    coefB1=calculate_coeeficient(p,q)[0]
    coefB0=target_mean-(coefB1*col_mean) 
    print(coefB0[0])

3174.57306038937
1360.2459447616366
12426.691632896143


In [422]:
def co_efficients(continuous_cols):
    target_mean=table[['charges']].apply(get_mean)
    co_effiecientsB1=[]
    co_effiecientsB0=[]
    for col in continuous_cols:
        table.dropna(subset=[col],inplace=True)
        col_mean=table[[col]].apply(get_mean).values[0]
        p=table[[col]].apply(get_deviation,args=([col_mean]))
        coefB1=calculate_coeeficient(p,q)[0]
        coefB0=target_mean-(coefB1*col_mean)                        
        print("Coeeficient B1 for {} is {}".format(col,coefB1))
        print("Coeeficient B0 (Bias) for {} is {}".format(col,coefB0[0]))
        co_effiecientsB1.append(coefB1)
        co_effiecientsB0.append(coefB0[0])
    return co_effiecientsB1,co_effiecientsB0
co_efficients(continuous_cols)   

CoeeficientB1 for age is 255.62441741687826
CoeeficientB0 for age is 3174.57306038937
CoeeficientB1 for bmi is 385.9534657139147
CoeeficientB0 for bmi is 1360.2459447616366
CoeeficientB1 for children is 699.6660150400287
CoeeficientB0 for children is 12426.691632896143


([255.62441741687826, 385.9534657139147, 699.6660150400287],
 [3174.57306038937, 1360.2459447616366, 12426.691632896143])